runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico


- url: /img
  static_dir: static/img

- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: /task/.*
  script: dispatch.tasks_app
  login: admin

- url: .*
  script: dispatch.site_app

libraries:
- name: lxml
  version: latest

builtins:
- appstats: on

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'
