runtime: python311
threadsafe: true
api_version: 1
app_engine_apis: true # from https://pypi.org/project/appengine-python-standard/

handlers:
- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico

- url: /img
  static_dir: static/img

- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: .*
  script: main.app

builtins:
- appstats: on

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'
